python_abi_tag:
 - cp37m
 - cp38
 - cp39
 - cp310
 - pypy36_pp73  # [not win64]
 - pypy37_pp73

python_impl_version:
 - 3.7
 - 3.8
 - 3.9
 - 3.10
 - 7.3   # [not win64]
 - 7.3

python_version:
 - 3.7
 - 3.8
 - 3.9
 - 3.10
 - 3.6     # [not win64]
 - 3.7

python_implementation:
 - cpython
 - cpython
 - cpython
 - cpython
 - pypy    # [not win64]
 - pypy

# Following are dummy keys to fix rerendering
python:
 - "2.7"
python_impl:
 - '*'
numpy:
 - '1.16'
c_compiler:
 - "*"
cxx_compiler:
 - "*"
vc:
 - "*"

zip_keys:
 -
   - python_abi_tag
   - python_version
   - python_impl_version
   - python_implementation
