# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_python_abi_tagcp310python_impl_version3.10python_implementationcpythonpython_version3.10:
        CONFIG: linux_64_python_abi_tagcp310python_impl_version3.10python_implementationcpythonpython_version3.10
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_python_abi_tagcp37mpython_impl_version3.7python_implementationcpythonpython_version3.7:
        CONFIG: linux_64_python_abi_tagcp37mpython_impl_version3.7python_implementationcpythonpython_version3.7
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_python_abi_tagcp38python_impl_version3.8python_implementationcpythonpython_version3.8:
        CONFIG: linux_64_python_abi_tagcp38python_impl_version3.8python_implementationcpythonpython_version3.8
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_python_abi_tagcp39python_impl_version3.9python_implementationcpythonpython_version3.9:
        CONFIG: linux_64_python_abi_tagcp39python_impl_version3.9python_implementationcpythonpython_version3.9
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_python_abi_tagpypy36_pp73python_impl_version7.3python_implementationpypypython_version3.6:
        CONFIG: linux_64_python_abi_tagpypy36_pp73python_impl_version7.3python_implementationpypypython_version3.6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_python_abi_tagpypy37_pp73python_impl_version7.3python_implementationpypypython_version3.7:
        CONFIG: linux_64_python_abi_tagpypy37_pp73python_impl_version7.3python_implementationpypypython_version3.7
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)