# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-11
  strategy:
    matrix:
      osx_64_python_abi_tagcp310python_impl_version3.10python_implementationcpythonpython_version3.10:
        CONFIG: osx_64_python_abi_tagcp310python_impl_version3.10python_implementationcpythonpython_version3.10
        UPLOAD_PACKAGES: 'True'
      osx_64_python_abi_tagcp311python_impl_version3.11python_implementationcpythonpython_version3.11:
        CONFIG: osx_64_python_abi_tagcp311python_impl_version3.11python_implementationcpythonpython_version3.11
        UPLOAD_PACKAGES: 'True'
      osx_64_python_abi_tagcp37mpython_impl_version3.7python_implementationcpythonpython_version3.7:
        CONFIG: osx_64_python_abi_tagcp37mpython_impl_version3.7python_implementationcpythonpython_version3.7
        UPLOAD_PACKAGES: 'True'
      osx_64_python_abi_tagcp38python_impl_version3.8python_implementationcpythonpython_version3.8:
        CONFIG: osx_64_python_abi_tagcp38python_impl_version3.8python_implementationcpythonpython_version3.8
        UPLOAD_PACKAGES: 'True'
      osx_64_python_abi_tagcp39python_impl_version3.9python_implementationcpythonpython_version3.9:
        CONFIG: osx_64_python_abi_tagcp39python_impl_version3.9python_implementationcpythonpython_version3.9
        UPLOAD_PACKAGES: 'True'
      osx_64_python_abi_taggraalpy_38_nativepython_impl_version3.8python_implementationgraalpypython_version3.8:
        CONFIG: osx_64_python_abi_taggraalpy_38_nativepython_impl_version3.8python_implementationgraalpypython_version3.8
        UPLOAD_PACKAGES: 'True'
      osx_64_python_abi_tagpypy38_pp73python_impl_version7.3python_implementationpypypython_version3.8:
        CONFIG: osx_64_python_abi_tagpypy38_pp73python_impl_version7.3python_implementationpypypython_version3.8
        UPLOAD_PACKAGES: 'True'
      osx_64_python_abi_tagpypy39_pp73python_impl_version7.3python_implementationpypypython_version3.9:
        CONFIG: osx_64_python_abi_tagpypy39_pp73python_impl_version7.3python_implementationpypypython_version3.9
        UPLOAD_PACKAGES: 'True'
      osx_arm64_python_abi_tagcp310python_impl_version3.10python_implementationcpythonpython_version3.10:
        CONFIG: osx_arm64_python_abi_tagcp310python_impl_version3.10python_implementationcpythonpython_version3.10
        UPLOAD_PACKAGES: 'True'
      osx_arm64_python_abi_tagcp311python_impl_version3.11python_implementationcpythonpython_version3.11:
        CONFIG: osx_arm64_python_abi_tagcp311python_impl_version3.11python_implementationcpythonpython_version3.11
        UPLOAD_PACKAGES: 'True'
      osx_arm64_python_abi_tagcp37mpython_impl_version3.7python_implementationcpythonpython_version3.7:
        CONFIG: osx_arm64_python_abi_tagcp37mpython_impl_version3.7python_implementationcpythonpython_version3.7
        UPLOAD_PACKAGES: 'True'
      osx_arm64_python_abi_tagcp38python_impl_version3.8python_implementationcpythonpython_version3.8:
        CONFIG: osx_arm64_python_abi_tagcp38python_impl_version3.8python_implementationcpythonpython_version3.8
        UPLOAD_PACKAGES: 'True'
      osx_arm64_python_abi_tagcp39python_impl_version3.9python_implementationcpythonpython_version3.9:
        CONFIG: osx_arm64_python_abi_tagcp39python_impl_version3.9python_implementationcpythonpython_version3.9
        UPLOAD_PACKAGES: 'True'
      osx_arm64_python_abi_taggraalpy_38_nativepython_impl_version3.8python_implementationgraalpypython_version3.8:
        CONFIG: osx_arm64_python_abi_taggraalpy_38_nativepython_impl_version3.8python_implementationgraalpypython_version3.8
        UPLOAD_PACKAGES: 'True'
      osx_arm64_python_abi_tagpypy38_pp73python_impl_version7.3python_implementationpypypython_version3.8:
        CONFIG: osx_arm64_python_abi_tagpypy38_pp73python_impl_version7.3python_implementationpypypython_version3.8
        UPLOAD_PACKAGES: 'True'
      osx_arm64_python_abi_tagpypy39_pp73python_impl_version7.3python_implementationpypypython_version3.9:
        CONFIG: osx_arm64_python_abi_tagpypy39_pp73python_impl_version7.3python_implementationpypypython_version3.9
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)